version: '3.8'

services:
  app:
    build: .
    restart: always
    volumes:
      # Isso garante que a sessão do WPP fique salva no disco do servidor
      - typebot_wpp_session:/app/auth_info
    environment:
      # Passa a variável que você vai configurar no painel do Dokploy
      - TYPEBOT_URL=${TYPEBOT_URL}

volumes:
  typebot_wpp_session: