version: '3.8'

services:
  app:
    build: .
    restart: always
    volumes:
      # Salva a sessão no disco do servidor para não pedir QR code toda hora
      - wpp_session_data:/app/auth_info_final
    environment:
      - TYPEBOT_URL=${TYPEBOT_URL}

volumes:
  wpp_session_data: